### ISSUE TITLE
Error: The number of shrink factors does not match the number of levels

### ISSUE THREAD

**Issue by zhao98** [ANTsX/ANTs#1102] opened 2020-10-15 06:34 UTC
Hello, I have used antsRegistrationSyN.sh command. However, there is an error now: 
**The number of shrink factors does not match the number of levels. 
Shrink Factors: 4 
Number Of Levels: 1**
I could see that the shrink factor is 8x4x2x1. But how to deal with the level? 
Could you help me with this? Thanks!

My command is: 
`antsRegistrationSyN.sh -d 3 -f /data/DWI_original_data/000/T1_brain.nii.gz -m /data/ANTs/Oasis/T_template0_BrainCerebellum.nii.gz -t r -x /data/ANTs/Oasis/T_template0_BrainCerebellumRegistrationMask.nii.gz -o /data/T1_reg.nii.gz`

T1_brain is my data, and T_template is the Oasis template.

**Comment by ntustison** [comment] 2020-10-15 15:48
The number of levels should be determined  automatically.  Can you provide the entire screen dump?

**Comment by zhao98** [comment] 2020-10-16 10:36
![图片1](https://user-images.githubusercontent.com/44949078/96248466-374ece80-0fde-11eb-8ed7-4a3f6b6dfc23.png)
![图片2](https://user-images.githubusercontent.com/44949078/96248482-3a49bf00-0fde-11eb-8054-f5f0d757d367.png)
![图片3](https://user-images.githubusercontent.com/44949078/96248489-3b7aec00-0fde-11eb-90d9-dc8f9d4a2fa3.png)
![图片4](https://user-images.githubusercontent.com/44949078/96248495-3d44af80-0fde-11eb-97af-12cd139e67df.png)
![图片5](https://user-images.githubusercontent.com/44949078/96248503-3e75dc80-0fde-11eb-91c2-b8553edaf5db.png)

**Comment by zhao98** [comment] 2020-10-16 10:47
These are the screenshots. I intend to registrate the Oasis template to my T1 data. And the size of T1_brain is 145x174x145. I could see 'number of levels = 1' , but I don't understand how to fix this.

**Comment by ntustison** [comment] 2020-10-16 12:56
I don't see how this is happening.  Is your repository up to date?  Also, I want to see your command line call included with the screenshots.

Also, if you only specify a single mask, it's going to assume that the mask is for the fixed image.  So you need to fix that but I don't believe that mistake is related to the incorrect number of levels.

**Comment by cookpa** [comment] 2020-10-16 15:35
Please include:

 * The exact command line as it was run. Please run all commands with
   verbose output where possible. If your command takes a long time, please try
   to produce a faster example that still shows the problem (eg, by running
   fewer iterations). 

 * The full verbose output printed to the terminal when you run the command. If
   this is very long, please paste into a text file and upload as an attachment.
 
 * Example input data that goes with the command line you provide. You
   can share your own data or link to any public data that reproduces the
   problem you are experiencing. If you cannot reproduce the problem with public
   data, please let us know which data sets you tried.

If uploading data as an attachment, please try to minimize the file size by
compressing, downsampling or otherwise creating smaller images that demonstrate
the problem.


**System information (please complete the following information)**
Many issues are specific to a particular system. Please include all information
about your computing environment.

 - OS: [e.g. Mac OS]
 - OS version: [e.g. 10.15.1]
 - Type of system: [Desktop, laptop, HPC cluster, cloud instance,
   other]
 
   If you are building inside a virtual machine, container, Cygwin, 
   Windows Subsystem for Linux, or other non-native environment, please 
   let us know and include details of both the virtual Linux and the 
   host OS.

**ANTs version information**
 - ANTs code version: [output of antsRegistration --version]
 - ANTs installation type: [Compiled from source, downloaded binary
   (from where?), installed by another package (which?), installed in
   container (URL?), other (please specify)]

**Additional information**
Add any other information that might help solve the problem.

**Comment by cookpa** [comment] 2020-10-16 15:38
Possibly related issues:

https://github.com/ANTsX/ANTs/issues/935
https://github.com/ANTsX/ANTs/issues/654

**Comment by cookpa** [comment] 2020-10-16 16:04
If the installed ANTs version is 2.3.0, it could be the bracket expansion bug.

https://github.com/ANTsX/ANTs/issues/712

To quickly test this, you could try downloading and running the latest version of the script

https://raw.githubusercontent.com/ANTsX/ANTs/master/Scripts/antsRegistrationSyN.sh

**Comment by zhao98** [comment] 2020-10-16 17:06
I have showed my command. My os is Ubuntu 16.04, installed on the server. And I am using ANTs 2.3. 
The command is
`antsRegistrationSyN.sh -d 3 -f /data3/xinyizhao/DWI_original_data/000/T1_brain.nii.gz -m /data3/xinyizhao/ANTs/Oasis/T_template0_BrainCerebellum.nii.gz -t r -o /data3/xinyizhao/T1_reg.nii.gz`
[T1_brain.nii.gz](https://github.com/ANTsX/ANTs/files/5393184/T1_brain.nii.gz) is the fixed data. 
[T_template0_BrainCerebellumRegistrationMask.nii.gz](https://github.com/ANTsX/ANTs/files/5393186/T_template0_BrainCerebellumRegistrationMask.nii.gz) is the moving data.
And I got this result [T1_reg.log](https://github.com/ANTsX/ANTs/files/5393188/T1_reg.log).
I couldn't understand how is 'level' calculated. The directions of the fixed data and moving data are different. Could this be the reason? I can't think of any other reason. Would you test this please?

**Comment by zhao98** [comment] 2020-10-16 17:17
The output of [antsRegistration --version] is 'ANTs Version: 2.2.0.dev242-g33bdc'. But I think I actually installed ANTs 2.3.

**Comment by cookpa** [comment] 2020-10-21 21:20
Your commit is after the 2.3 release. The version information that ends up in the executables is determined at build time by CMake, and it doesn't like certain kinds of git tags.

Here's the version you have

https://github.com/ANTsX/ANTs/commit/33bdcd0fd9085eeaa69288c612bb3bedb436f565

There was a bracket expansion issue in the ANTs shell scripts that has since been fixed, so if you can update your ANTs install, it might solve the problem.

**Comment by cookpa** [comment] 2020-11-02 16:21
Closing for now but can revisit if there's more information.

**Closed by cookpa** 2020-11-02 16:21 UTC

**Comment by tashrifbillah** [comment] 2022-01-05 04:49
Hi Philip, I have had v2.3.0 and your https://github.com/ANTsX/ANTs/issues/1102#issuecomment-710145601 solved that issue.

**Comment by yerhi** [comment] 2022-04-06 12:05
Hello,

I am getting the same error during Registration. 

"The number of shrink factors does not match the number of levels."

The strange thing is that I have processed the same (and other more) subject (s) on the same PC and I have not gotten this error before. I have not made any changes on the software as far as I am aware. I have tried to repeat the processing with other subject and I keep getting the same error. 

If I understand correctly ANTs reads some info from the images and determines the number of levels, would it be possible then that the error is coming from some of the previous steps?  And how could I test this? I can compare the output files and headers from my previous analyses that went fine and the recent ones.

I attached the log file (it comes from a pipeline that uses different software).  

Thanks!

[03_T1_Processing.log](https://github.com/ANTsX/ANTs/files/8426632/03_T1_Processing.log)

**Comment by ntustison** [comment] 2022-04-06 14:40
Can you try running outside of Matlab?

**Comment by yerhi** [comment] 2022-04-07 10:27
I was running from bash. The same as the previous times when it was working

**Comment by yerhi** [comment] 2022-04-07 10:33
Here is the command:

                        ${ABIN}/antsRegistration -d 3 -r [$REF,$SRC,1] -v 1 \
                                    -m MI[$REF,$SRC,1,128] -t translation[0.2] -c [500x250,1.e-8,20] \
                                    -s 3x4vox -f 3x2 -l 1 -n BSpline \
                                    -m MI[$REF,$SRC,1,128,Regular,0.5] -t rigid[0.1] -c [500x250,1.e-8,20] \
                                    -s 3x2vox -f 3x2 -l 1 -n BSpline \
                                    -o [${ANATDIR}/anat2native,${ANATDIR}/anat2native.nii]

This was working and I didn't make changes to the script either....

**Comment by ntustison** [comment] 2022-04-07 14:15
The original log file you posted showed Matlab being invoked somehow along with several other confusing errors which is why I asked.  

You can type the command line and add ``--help`` which will show you what the command line processed.  Please post the output here.

**Comment by yerhi** [comment] 2022-04-08 09:11
Hello,

Yes, it was the log file from a pipeline that uses different software for different parts of the processing. 

Here is the output from the specific Registration step with ANTs. 

Now, ANTs registers: Number of levels:1

Before it was detecting Number of levels: 2.

How is that ANTs detects the number of levels? And what does number of levels refers to?

Thanks!
[03_T1_Processing.log](https://github.com/ANTsX/ANTs/files/8450418/03_T1_Processing.log)

**Comment by ntustison** [comment] 2022-04-08 13:17
I also want to see the output of your command with the ``--help`` option included.  Please include both the command and the output.

**Comment by cookpa** [comment] 2022-04-08 13:24
Is it bracket shell expansion, as was the case earlier in this thread? Does this work?

```
 ${ABIN}/antsRegistration -d 3 -r [ $REF,$SRC,1 ] -v 1 \
                                -m MI[ $REF,$SRC,1,128 ] -t translation[ 0.2 ] -c [ 500x250,1.e-8,20 ] \
                                -s 3x4vox -f 3x2 -l 1 -n BSpline \
                                -m MI[ $REF,$SRC,1,128,Regular,0.5 ] -t rigid[ 0.1 ] -c [ 500x250,1.e-8,20 ] \
                                -s 3x2vox -f 3x2 -l 1 -n BSpline \
                                -o [ ${ANATDIR}/anat2native,${ANATDIR}/anat2native.nii ]
```

**Comment by yerhi** [comment] 2022-04-08 14:19
Hi!

I added the --help and --verbose at the end but I was receiving an error. 

The good news are that the bracket expansion worked! I thought that I just needed to update the ANTs registration script. I am still puzzled on why it was working before on the same system with the same data and then stopped working (maybe a change of which I was not aware?). But the important thing is that is working now.

Thank you very much both for your help!

**Comment by cookpa** [comment] 2022-04-08 14:23
When you put things in a square bracket, bash attempts to match it to files in the current directory. So the behavior depends on the state of the current working directory. For example, starting in an empty directory,

```
bash-3.2$ echo [abc]
[abc]
bash-3.2$ touch a
bash-3.2$ echo [abc]
a
``` 

Using spaces around the brackets prevents this

```
bash-3.2$ echo [ abc ]
[ abc ]
```

**Comment by yerhi** [comment] 2022-04-08 14:27
Ohhh, thanks for the explanation!

Still I am wondering what happened, would  a change in bash create the difference? Before everything was working in bash without the expansion...
