### ISSUE TITLE
Ants Longitudinal CT Template-Build Stage fail

### ISSUE THREAD

**Issue by dbrennan44** [ANTsX/ANTs#1634] opened 2023-12-12 18:33 UTC
Hi all,

ANTs Longitudinal Cortical Thickness is failing at the template-building stage with 2 scans. Oddly, this behavior does not happen each time antsCT is run (rerunning a subject can work). Here is an example output with error message:

*output is attached for formatting* 
[output.txt](https://github.com/ANTsX/ANTs/files/13652019/output.txt)

I can provide the two images if it helps diagnose.

Thank you!

**Comment by cookpa** [comment] 2023-12-12 18:47
What's your ANTs version?

**Comment by dbrennan44** [comment] 2023-12-12 18:50
ANTs Version: v2.4.1.post7-g71c9890

from antsRegistration

**Comment by cookpa** [comment] 2023-12-12 18:57
Might be data-dependent. I think this arises from scales estimation in the beginnings of registration

https://discourse.itk.org/t/zero-valued-spacing-is-not-supported-and-may-result-in-undefined-behavior/5382/6
https://github.com/ANTsX/ANTs/issues/1348

Will try to reproduce with data

**Comment by dbrennan44** [comment] 2023-12-12 19:09
[here is a link](https://drive.google.com/file/d/1U1v35NgDJ55Rk-5rhjgeBs6qQwVDpRZX/view?usp=sharing)

I will note, I manually truncated the images before processing because the FOV was very large and included the neck.

**Comment by cookpa** [comment] 2023-12-12 23:10
Thanks, the images look like they should work. This works for me on Mac OS using 2.5.0.post12-g9516f51 (I ran it twice)

`
antsMultivariateTemplateConstruction.sh -d 3 -o template -b 0 -g 0.25 -i 4 -c 2 -j 4 -k 1 -w 1 -m 100x70x30x3 -n 1 -r 1 -s CC -t GR -y 1 -z scan_a.nii.gz scan_a.nii.gz scan_b.nii.gz
`

**Comment by dbrennan44** [comment] 2023-12-13 16:31
great! My problem was happening within a call to antsLongitudinalCorticalThickness.sh. Can the templates be built outside of this script and used? Perhaps an initial template?

**Comment by cookpa** [comment] 2023-12-13 16:48
Right, I used the template command from your original output.txt, which doesn't include the original call to the longitudinal script. Unfortunately it's not easy to use an initial template with that script.

We might debug further if you can try running the longitudinal script with `-b 1` to keep temporary files. When it fails, does it leave behind a template `T_template0.nii.gz`? If the template is blank for some reason, the next iteration may fail with the error message you saw.

Also if you can add the original call to antsLongitudinalCorticalThickness.sh I'll try to reproduce the whole script call.

**Comment by dbrennan44** [comment] 2023-12-13 18:22
[heres the Template folder](https://drive.google.com/file/d/1CxwPjpp0eYWl6UenONUL2KWAGlfpBSFe/view?usp=sharing)

there are a lot of intermediate templates

**Comment by cookpa** [comment] 2023-12-13 18:38
Thanks! The template failed and is blank, which creates the error. Possibly related, I see that your input file names are identical - this will cause problems. 

This is definitely something we should check for and fix at run time. Meanwhile, you might try changing the input files to MPRAGE_baseline.nii.gz and MPRAGE_followup.nii.gz

**Comment by dbrennan44** [comment] 2023-12-13 19:50
I will try this and report, good to know! Previous successful runs with different data had different file names!

**Comment by dbrennan44** [comment] 2023-12-14 16:27
I ran two subjects after changing the image basenames, and both ran thru antsLongitudinalCorticalThickness successfully. Think this was the problem, especially because a control cohort (1 scan each) ran fully successfully with no issue. Thank you!

**Comment by cookpa** [comment] 2023-12-14 16:29
Great, thanks for sharing the info to help track this down! I think it is a simple fix to make the template scripts name their output uniquely. The longitudinal script already does this, so it should be fixed now.

**Closed by cookpa** 2023-12-14 16:29 UTC
Labels: bug
