### ISSUE TITLE
NIFTI_SYSTEM_MATH_LIB

### ISSUE THREAD

**Issue by pinilorenzo** [ANTsX/ANTs#1514] opened 2023-03-19 19:49 UTC
Dear all,

I'm trying to install ANTs in Ubuntu 20.04.5 LTS (Focal Fossa) but I got the following CMake Error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NIFTI_SYSTEM_MATH_LIB (ADVANCED)
Attached the log files
[cmake.log](https://github.com/ANTsX/ANTs/files/11012117/cmake.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/11012118/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/11012119/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/11012120/CMakeOutput.log)
[build.log](https://github.com/ANTsX/ANTs/files/11012116/build.log)

The error happend after I tried to re-installed ANTs after removing the folder of the first installation
[](url)
Any idea?
Thanks

**Comment by cookpa** [comment] 2023-04-28 17:55
Reading a bit more about this, it appears to arise from missing `libm`, which might be either because it's missing from the system, or not visible in the fsl conda environment. 

The dependency on libm might be fixed in a future ITK release.

Possible workaround is to add the cmake variable "-D NIFTI_SYSTEM_MATH_LIB= "

ANTs builds on Github runners using Ubuntu focal work normally, as do my local builds on that OS.

Closing for now

**Closed by cookpa** 2023-04-28 17:55 UTC

**Comment by 19990929mia** [comment] 2023-10-23 12:09
I figure out this problem. It may caused by the version of ccmake (especially the first time I use 3.21.xx). You can download another version and try again, it will be fixed.

**Comment by cookpa** [comment] 2023-10-23 12:21
Many thanks for updating
