### ISSUE TITLE
antsMultivariateTemplateConstruction2.sh using Yucatan minipig brains?

### ISSUE THREAD

**Issue by jlisinski** [ANTsX/ANTs#1108] opened 2020-10-26 19:09 UTC
Hello,

I tried running antsMultivariateTemplateConstruction2.sh (ANTs 2.3.2) on 58 manually skull-stripped and ACPC-aligned Yucatan minipig brains (T1-weighted; 1x1x1 mm^3), but the generated template in not recognizable as a brain, unfortunately. I used the default command-line options as described in the help, but I am new to ANTs and probably doing something wrong. I am also not sure how much these options are tailored towards human brains and if ANTs can be tweaked to work with pig brains. When I ran the same command on similar human data, the generated template was stunning. I am hoping for some suggestions/guidance/help from the ANTs developers/community. The data is publicly available on [gihub](https://github.com/lacontelab/VT-Yucatan-MRI-Template) and the antsMultivariateTemplateConstruction2.sh script can be executed by cloning the git repo and by running ants.sh in the ants directory. I also uploaded a tarball of the output [here](https://drive.google.com/file/d/1D1mk55C8LySB05Wul4Q5Mle6yO8Zpb6P/view?usp=sharing) (1.7 GB). Any help is appreciated. Thanks a lot in advance!      

Best,
Jonathan

**Comment by gdevenyi** [comment] 2020-10-27 00:37
Dealing with files touched by other NIFTI software is a dangerous game since the standards-compliance of other software is highly variable. Some NIFTI files generated from the original DICOMs (dcm2niix) is a good place to start working with the ANTs software

**Comment by jlisinski** [comment] 2020-10-27 16:58
Thanks for your reply. We only used AFNI for ACPC alignment and manual skull-stripping prior to ANTs. Bob Cox who started the AFNI software package also spearheaded the [NIFTI ](https://nifti.nimh.nih.gov/) format at the NIH and thus I am confident that AFNI programs are "in compliance" with the format.  Could you give me more details why you think the .nii files created from AFNI's HEAD/BRIK are problematic for ANTs?

**Comment by ntustison** [comment] 2020-10-27 17:17
I can't find the data on your GitHub website.  The link in the README points to a non-existent location.  Regardless, in debugging template-building issues, you might want to start with a small subset (like 3) and see what you can generate.  We can proceed from there.

Any potential nifti issues that we encounter is not compliance with the standard but rather with the fact that different packages use the header information differently.  Specifically, we encounter [this issue](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F) most often.

**Comment by gdevenyi** [comment] 2020-10-27 17:33
> Could you give me more details why you think the .nii files created from AFNI's HEAD/BRIK are problematic for ANTs?

As per @ntustison this is less compliance and more "interpretation" of the standard.

**Comment by lacontelab** [comment] 2020-10-27 17:54
@ntustison Thanks for your help! I see what the issue with NIFTI is now. I will inspect the header entries and ensure that sform/qform entries are set properly in the header to run ANTs and then try again with 3 subjects to debug.
Sorry about the 404, I updated the README file. The data is [here](https://github.com/lacontelab/VT-Yucatan-MRI-Template/releases/download/v0.1.1/MRI_data_n70_AFNI_v0.1.tar.gz) if you are still interested. Thanks again!

**Comment by jlisinski** [comment] 2020-10-28 22:05
I checked the sform and qform after conversion to .nii (using AFNI's 3dcopy) for all 58 subjects and they are identical. Here is one example:

> qform_code    1
> qto_xyz:1      -1.000000  0.000000  0.000000  95.000000
> qto_xyz:2      0.000000  -1.000000  0.000000  95.000000
> qto_xyz:3      0.000000  0.000000  1.000000  -70.000000
> qto_xyz:4      0.000000  0.000000  0.000000  1.000000
> qform_xorient  Right-to-Left
> qform_yorient  Anterior-to-Posterior
> qform_zorient  Inferior-to-Superior
> sform_name     Scanner Anat
> sform_code     1
> sto_xyz:1      -1.000000  -0.000000  -0.000000  95.000000
> sto_xyz:2      -0.000000  -1.000000  -0.000000  95.000000
> sto_xyz:3      0.000000  0.000000  1.000000  -70.000000
> sto_xyz:4      0.000000  0.000000  0.000000  1.000000

Any other ideas what might be going on?

**Comment by ntustison** [comment] 2020-10-28 22:08
What about the small subset experiment?

**Comment by jlisinski** [comment] 2020-10-28 22:11
I haven't run it because the qform and sform are identical and should not be an issue. I'll run it and let you know.

**Comment by gdevenyi** [comment] 2020-10-28 23:13
@jlisinski If you can release some NIFTI files I experiment to see what's going on.

**Comment by cookpa** [comment] 2020-10-28 23:37
Yes some nifti for the small experiment would be helpful

Sent from my iPhone

On Oct 28, 2020, at 7:14 PM, Gabriel A. Devenyi <notifications@github.com> wrote:

﻿

@jlisinski<https://github.com/jlisinski> If you can release some NIFTI files I experiment to see what's going on.

**Comment by jlisinski** [comment] 2020-10-29 04:22
Sorry for the delay. I ran it for three subjects. The template looks like a brain now, but the alignment is not great, unfortunately. [Here](https://drive.google.com/file/d/1M0h9-19YnEVg9NVCfchBWovfpJ5EW9j4/view?usp=sharing) is a tarball with all of the .nii files (70 subjects total). The output from the 3-subject analysis is in the ants directory. This directory also contains the script (ants.sh) I ran. Thanks for your help!

**Comment by cookpa** [comment] 2020-10-29 20:44
I'm looking at the example now. I think better initialization might help.

Something like

```
antsMultivariateTemplateConstruction2.sh -d 3 -i 3 -k 1 \
  -z <one of the images> \
  -r 1 \
  -f 4x2x1 -s 2x1x0vox -q 50x100x25 -t Affine  -m MI -c 2 -o ANTS_affine $dsets | tee -a ants.log 2>&1
```

If this looks reasonable, you can use the output of this step as input to another template construction call (with -z and -r 0) using SyN.

I think the problem is that it's jumping into large deformation with a very blurry initial template.

**Comment by jlisinski** [comment] 2020-10-30 04:37
Thanks a lot for taking a look. I will give this a try.

**Comment by gdevenyi** [comment] 2020-10-30 19:00
Hi,

A ran most of modelbuild before a power outage here. I wasn't at all happy with the results. The brain extraction of these subjects is pretty hairy, and edge matching is a very strong signal for ANTs nonlinear registration, I wonder if it would be worth trying this with the original native images.

![image](https://user-images.githubusercontent.com/3001850/97746366-97567200-1ac0-11eb-952f-a23e0a0f6081.png)

**Comment by jlisinski** [comment] 2020-11-02 19:03
@gdevenyi Thank you for running this! Sorry to hear about the power outage. Besides the edges, this template looks very good to me. We tried alignment with the full head (after ACPC alignment) in AFNI, but alignment was not good.  [Here](https://drive.google.com/file/d/1U4g3HMyszQEJAb8WAvcw8PE9-P_QjrTE/view?usp=sharing) (940 MB) are the .nii files directly after DICOM conversion and after ACPC alignment (before skull stripping) if you like to try. Could you share the ANTs commands you used to generate this template? I would like to reproduce and also try generating one using the full-head data as you suggested. Thanks again!

**Comment by gdevenyi** [comment] 2020-11-02 19:31
1) I used `ThresholdImage` to generate an Otsu mask for every brain, and then ran N4BiasFieldCorrection using that as a mask with the typical defaults to get better bias field correction
2) I used `AverageImages` to generate an average of all the brains, then thresholded using `ThresholdImage` and `ExtractRegionFromImageByMask`to re-crop an initial target, and upsampled the target to 0.5mm isotropic using `ResampleImage`
3) I ran this modelbuild:
```
> ./antsMultivariateTemplateConstruction2.sh -d 3 -r 0 -n 0 -z intial-target.nii.gz \
-q 500x500x500x500x500x500x500x500x500x500x500x500x500x500x225x75x25 \
-f 7x7x7x7x7x7x7x7x7x7x7x6x5x4x3x2x1 \
-s 3.60336722636x3.39064538209x3.1778711878x2.96503337341x2.75211717859x2.53910288566x2.32596354299x2.11266130337x1.89914128022x1.68532069997x1.47106851007x1.25616388301x1.04020251906x0.822352297022x0.600561204393x0.367767127519x0.0mm \
../data/*/t1*n4.nii.gz
```
Pyramid scheme was generated by my ANTs registration generation tool (https://github.com/CoBrALab/minc-toolkit-extras/blob/master/ants_generate_iterations.py) which bases it off the maximum extent of the image and the minimum resolution of the fixed space.

**Comment by jlisinski** [comment] 2020-11-02 20:17
Thanks for sharing your pipeline! I will try to reproduce.

**Comment by gdevenyi** [comment] 2020-11-05 15:20
In progress of the non-extracted brains, N4 corrected, and reoriented *without* resampling, as the ACPC alignment has reduced the scan quality with resampling interpolation. This is in-progress 1st round SyN/CC modelbuild.

![image](https://user-images.githubusercontent.com/3001850/98259796-8e4a2280-1f50-11eb-8f50-368ff239d5c8.png)

**Comment by jlisinski** [comment] 2020-11-05 17:53
Thank you so much! Very cool and exciting! For how many subjects is the screenshot? Are you initializing the template build for each subject with a transformation matrix to reorient without resampling? Could you share your ANTs script and required data so I can reproduce? This is amazing. Thank you for all of your help!

**Comment by gdevenyi** [comment] 2020-11-05 19:41
This is ~35 subjects into the first round of non-linear modelbuilding.

> Are you initializing the template build for each subject with a transformation matrix to reorient without resampling?
I rewrote the coordinate system for each scan so that it ended up in the same orientation as your ACPC scans, then I did a sort of dumb average of the initial scans.

> Could you share your ANTs script and required data so I can reproduce? This is amazing. Thank you for all of your help!
I'll automate all the steps I did into a set of scripts and push up a full repo onto github.

**Comment by jlisinski** [comment] 2020-11-05 21:28
Great - thank you!!!

**Comment by gdevenyi** [comment] 2020-11-07 20:01
Scripts up at https://github.com/gdevenyi/yucatan_minipig_template

Modelbuilding goes as

0. preprocessing (reorient & n4)
1. dumb average using COM to initialize modelbuild
2. rigid modelbuild
3. affine modelbuild
4. nlin modelbuild
5. upsampling to 0.5 mm isotropic and recropping ROI
6. final modelbuild at 0.5 mm resolution

Current model, up to step 4 is complete:
![image](https://user-images.githubusercontent.com/3001850/98450345-0c9df480-210a-11eb-803c-29ca72c2ab4c.png)

**Comment by jlisinski** [comment] 2020-11-09 17:57
Wow! This template looks amazing already! Thank you very much! I will take a look a the git repo and try to reproduce.

**Comment by gdevenyi** [comment] 2020-11-09 18:40
Intermediate of the upsampled model, last round still running:
![image](https://user-images.githubusercontent.com/3001850/98582497-0b4b0400-2291-11eb-8f0c-fa9452322fed.png)

**Comment by gdevenyi** [comment] 2020-11-10 14:50
The final model:
![image](https://user-images.githubusercontent.com/3001850/98689508-00987980-233a-11eb-9a3f-910f1502591d.png)

I'm happy to package up these files and share them.

**Comment by hjmjohnson** [comment] 2020-11-10 15:32
@gdevenyi   We would love to have access to this data!  Please let us know how we may contribute/participate in this project.

**Comment by gdevenyi** [comment] 2020-11-10 15:45
Yes, I'll be happy to share widely, I just want to give @jlisinski first crack at this since he put the effort in of organizing the raw data for this experiment. I expect he'll want to produce some priors on this (brainmask and GM/WM/CSF classifications) to compliment his prior data release.

**Comment by hjmjohnson** [comment] 2020-11-10 15:49
That is exactly what we are working on as well!  Perhaps we could meet and discuss possible ways to collaborate and build better mini-pig analysis tools!  

We have done similar atlas building a few years ago, but were unable to make progress at that time due to limited resources. We have a small amount of pilot funding now that we can dedicate to supporting mini-pig analysis pipelines.

**Comment by gdevenyi** [comment] 2020-11-10 16:10
I'm definitely interested in collaborating, I've been slowly collecting a menagerie of animal (and unique human) analysis results using ANTs + my DBM wrapper (https://github.com/CoBrALab/twolevel_ants_dbm)

https://zenodo.org/record/3687254
http://cobralab.ca/posters/Devenyi.GA.OHBM.Chimp.2020.pdf (paper soon)
https://academic.oup.com/neurosurgery/advance-article-abstract/doi/10.1093/neuros/nyaa378/5918983
https://www.biologicalpsychiatryjournal.com/article/S0006-3223(20)30487-X/abstract (paper soon)
https://github.com/CoBrALab/RABIES (small animal fMRI built on modelbuild common space)

Seems as though minipigs are a growing model animal choice, definitely would be worth providing some nice priors and an analysis pipeline

**Comment by jlisinski** [comment] 2020-11-12 21:38
@gdevenyi Thanks for all of your help!!! The full FOV template looks amazing. Please feel free to package it up and share. It would be great if you could include a reference to our [gihub repo](https://github.com/lacontelab/VT-Yucatan-MRI-Template) and [preprint ](https://www.biorxiv.org/content/10.1101/2020.07.17.209064v1) when sharing this. We would also like to include this ANTs template in our release if that's okay with you. @hjmjohnson thank you for your interest!!! We are happy to work with you all on future minipig templates, atlases and analysis tools.

**Comment by gdevenyi** [comment] 2020-11-19 02:17
I uploaded the full template attached to a tagged release on my github:
https://github.com/gdevenyi/yucatan_minipig_template/releases

**Comment by gdevenyi** [comment] 2020-11-19 02:20
If you want the warp fields, etc please let me know and I'll figure out a way to package the huge thing up to share.

**Comment by lacontelab** [comment] 2020-11-19 18:33
Great! Thank you very much!

**Comment by cookpa** [comment] 2021-02-09 18:15
Closing but feel free to follow up with more comments

**Closed by cookpa** 2021-02-09 18:15 UTC

**Comment by gdevenyi** [comment] 2021-04-06 17:14
I've now spent a little time to create a clone of `antsMultivariateTemplateConstruction2.sh` which implements my scale-space optimized registrations as well as being driven by https://github.com/pipitone/qbatch the cluster job submission tool I maintain, https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction.

It does not implement the full set of features/options (yet). See the missing features section in the readme, however it does implement the principles used on the minipig.
