### ISSUE TITLE
ANTs compilation failed

### ISSUE THREAD

**Issue by Authenty** [ANTsX/ANTs#1034] opened 2020-06-28 09:45 UTC
Before opening an issue, please review the build documentation here

https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS

If you are building the latest code snapshot, please also check Travis
to see if the code is building successfully

https://travis-ci.org/ANTsX/ANTs

If you are using system ITK or VTK, please verify you have the correct
versions (see the Wiki link above). If you can, please also attempt a
Superbuild and let us know if that compiles successfully.

**When did the error occur?**

[ ] Compilation (make)

**Build environment**
 **- OS: [e.g. Mac OS Sierra]
 - OS version: [e.g. 10.12.6]
 - Type of system: [laptop]**
 
  **No--** If you are building inside a virtual machine, container, Cygwin, 
   Windows Subsystem for Linux, or other non-native environment, please 
   let us know and include details of both the virtual Linux and the 
   host OS. 
 
**ANTs version**
Specify the release tag or commit hash of the code you are building
from. If you downloaded a snapshot as a ZIP file, please provide the
date of the download.
--Sorry, I am not sure about the details about the release tag or commit hash of the code 

**Build configuration and logs**
Please attach the following files (relative to your build directory)

  - build.log (the terminal output from make)
  - CMakeCache.txt
  - CMakeFiles/CMakeError.log
  - CMakeFiles/CMakeOutput.log

**Additional context**

I started all these things using a bash method
1. cd /Users/authenty/Desktop/IPCAS_2/fMRI_BM/antsInstallExample-master
2. bash installANTs.sh 

[build.log](https://github.com/ANTsX/ANTs/files/4842024/build.log)
[cmake.log](https://github.com/ANTsX/ANTs/files/4842025/cmake.log)
[CMakeCache.txt](https://github.com/ANTsX/ANTs/files/4842026/CMakeCache.txt)
[CMakeError.log](https://github.com/ANTsX/ANTs/files/4842028/CMakeError.log)
[CMakeOutput.log](https://github.com/ANTsX/ANTs/files/4842029/CMakeOutput.log)

**Comment by cookpa** [comment] 2020-06-29 14:56
This is an interesting one. I think the problem is here

```
/bin/sh: /private/var/folders/f_/8d784b4959xcvp03ynhyq4z80000gn/T/AppTranslocation/52DFEE9A-C3E2-4B70-9749-ECA1A422D110/d/CMake.app/Contents/bin/cmake: No such file or directory
```

This suggests that app translocation, a security feature of Mac OS, has been activated. This might cause problems for the build. 

It might be possible to fix by downloading CMake again, and dragging the app to /Applications in Finder. According to what I've read, a command line move won't fix the problem. I'm just going from Google here. I install CMake as a unix tool through Homebrew, so I've not dealt with this problem before.

**Comment by Authenty** [comment] 2020-06-30 01:46
> This is an interesting one. I think the problem is here
> /bin/sh: /private/var/folders/f_/8d784b4959xcvp03ynhyq4z80000gn/T/AppTranslocation/52DFEE9A-C3E2-4B70-9749-ECA1A422D110/d/CMake.app/Contents/bin/cmake: No such file or directory
> 
> This suggests that app translocation, a security feature of Mac OS, has been activated. This might cause problems for the build.
> It might be possible to fix by downloading CMake again, and dragging the app to /Applications in Finder. According to what I've read, a command line move won't fix the problem. I'm just going from Google here. I install CMake as a unix tool through Homebrew, so I've not dealt with this problem before.

Dear Cook, thanks a lot for your kind help!
I think you might be right. I have fixed this problem by doing two things: first, installing Cmake again to the Applicatoins folder; second, installing Xcode to my mac. So, this reported error is likely a result of failure in preparation/configuration of the environment.

**Closed** 2020-07-01 15:08 UTC
