### ISSUE TITLE
Image units disrupts display range

### ISSUE THREAD

**Issue by Robkozol** [ANTsX/ANTs#1114] opened 2020-11-18 14:21 UTC
Hello,

When I save my confocal brain stacks as nifti files in fiji, the property units are changed from microns to pixels. If I leave the units as pixels, my registered brains come out looking normal. However, if I go back and change the units to microns, then my registered stacks are returned with no image, and a display range of 0-0.

I would like to have everything in microns, because I am using a 3rd party program to measure differences in brain volume between two populations of fish brains.

Thank you,
Rob

**Comment by ntustison** [comment] 2020-11-18 14:58
This sounds like a fiji problem.  Why not ask those developers?

**Comment by cookpa** [comment] 2021-02-09 14:55
ITK prefers to use mm units because of its close association with DICOM. If you give it an image in microns the spacing will get scaled by 10^{-3}. 

I'm going to close this for now but feel free to submit another issue following the bug report template, preferably with some example data. I'm not sure if the problem is really in the registration or in the conversion back to microns.

**Closed by cookpa** 2021-02-09 14:55 UTC
