### ISSUE TITLE
ANTS vs antsRegistration

### ISSUE THREAD

**Issue by anagrammarian** [ANTsX/ANTs#1073] opened 2020-08-28 17:49 UTC
For our thalamic segmentation project (THOMAS), we had been using ANTS command for nonlinear registration. However, I read about possible deprecation and switched to antsRegistration. Try as much as I have, I cannot match the quality of ANTS esp in cases with large ventricles. I cannot find much documentation on this.  
I used this https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call   and 
https://wiki.uiowa.edu/display/BRAINSPUBLIC/ANTS+conversion+to+antsRegistration+for+same+data+set
as guidelines.

My final command used tips from the Iowa experiment. Note that our images are quite small 70x100x70  order of. This is because I crop the images to focus on the thalamic regions and to increase speed. 

I give below both ANTS (old) and antsRegistration (new) commands.

ANTS 3 -m CC[/home/tyson/thomas/templ_93x187x68.nii.gz,temp/crop_LIFUP020_MPRAGE_WMn.nii.gz,1,5] -t SyN[0.25] -r Gauss[3,0] -o temp/LIFUP020_MPRAGE_WMn -i 30x90x20 --use-Histogram-Matching --number-of-affine-iterations 10000x10000x10000x10000x10000 --MI-option 32x16000 

antsRegistration -d 3 --float 0 --output temp/LIFUP020_MPRAGE_T1 -t Affine[0.1] --metric MI[/home/manojsar/thomas/templ_93x187x68.nii.gz,temp/crop_LIFUP020_MPRAGE_T1.nii.gz,1,32,Regular,0.25] -r [rigid0GenericAffine.mat,1] --convergence [1000x500x250x100,1e-6,10] -f 8x4x2x1 -s 3x2x1x0vox -t SyN[0.25,3.0] --metric CC[/home/manojsar/thomas/templ_93x187x68.nii.gz,temp/crop_LIFUP020_MPRAGE_T1.nii.gz,1,4] --convergence [70x90x50,1e-6,10] -f 4x2x1 -s 2x1x0vox

Note that I use the rigid0GenericAffine.mat which is the rigid regn of the uncropped images to the antsRegistration to initialize. This helped a lot.

Anything I am doing suboptimally with antsRegistration? The results are different, antsRegistration seems to underestimate slightly and it does poorly in large ventricles. ANTS does a stellar job.

I have tried all kinds of tweaks including #levels etc and doesn't make a difference.

Thanks
manoj

**Comment by gdevenyi** [comment] 2020-08-28 17:54
https://github.com/ANTsX/ANTs/wiki/ANTS-and-antsRegistration

**Comment by anagrammarian** [comment] 2020-08-28 17:56
Yes I have followed what is in that and it didn't help.

**Comment by ntustison** [comment] 2020-08-28 18:02
``antsRegistration`` is a complete refactoring so identical, explicit parameter sets might not produce the same solution.    However, in your case, you're using different radii.  Other than that, you'll have to do some parameter exploration on your own.

**Comment by gdevenyi** [comment] 2020-08-28 18:03
ANTS:
``CC[/home/tyson/thomas/templ_93x187x68.nii.gz,temp/crop_LIFUP020_MPRAGE_WMn.nii.gz,1,5] ``
antsRegistration
``CC[/home/manojsar/thomas/templ_93x187x68.nii.gz,temp/crop_LIFUP020_MPRAGE_T1.nii.gz,1,4]``
Different ^

ANTS
--use-Histogram-Matching
antsRegistration
missing

**Comment by anagrammarian** [comment] 2020-08-28 18:08
I have tried the 4,5 thing and didn't seem to help. I get spectacular registration with enlarged ventricles with ANTS and it is not anywhere close with antsRegistration. With normal cases, it is much closer but still if you look closely ANTS is better.  I am not sure I tried the --use-Histogram-Matching option. Will try but not hopeful.

**Comment by anagrammarian** [comment] 2020-08-28 18:23
I am trying the histogram and radius matching one more time. As I mentioned, I have spent hours playing and you can see even in the iowa experiments, ANTS performed better than antsRegistration. Their differences are more subtle. Mine are obvious. 

Can I just go back to ANTS? Is it going to be deprecated any time soon?

**Comment by gdevenyi** [comment] 2020-08-28 18:25
Not just the 4,5 thing, you're providing different input files.

**Comment by anagrammarian** [comment] 2020-08-28 18:28
No they are the same files. They are in different locations. Trust me I know what I am doing :)

**Comment by ntustison** [comment] 2020-08-28 18:29
I don't know where you're getting performance assessment that ANTS > antsRegistration from the UIowa experiments.  As developers, if it were indeed the case that ANTS performed consistently better than antsRegistration, we would have attempted to correct that a long time ago.  However, we're not considering getting rid of ANTS so you're welcome to continue using it.

**Comment by anagrammarian** [comment] 2020-08-28 20:48
I did it with both ANTs and antsRegistration. Same parameters as above except I added histogram matching and radius is 5 to match it almost exactly. 
![image](https://user-images.githubusercontent.com/25040406/91613766-05ea4880-e935-11ea-8d1e-24bfc15bf736.png)

The right image registration is clearly poorer esp near the ventricles (arrow) and the thalamus is squished up. This is reflected in segmentation volumes as well.

**Comment by anagrammarian** [comment] 2020-08-28 22:00
Would it help if I uploaded the 2 files (source and destination)?

**Comment by cookpa** [comment] 2020-08-28 22:13
The most effective way for us to help is with a reproducible example, including data and scripts, such that we can download and run them without modification (except that we'd be using our own ANTSPATH).

**Comment by gdevenyi** [comment] 2020-08-28 23:12
@anagrammarian you may be interested in my ants_generate_iterations.py script: https://github.com/CoBrALab/minc-toolkit-extras/blob/master/ants_generate_iterations.py for generating smooth steps down the image pyramid.

With the ```--output affine``` mode for generating a constrained path through the affine space and ``--output generic`` for generating options for SyN

**Comment by anagrammarian** [comment] 2020-08-28 23:40
Philip, here are the source and destination files.. The ANTS command used was 
ANTS 3 -m CC[templ_93x187x68.nii.gz,crop_LIFUP020_MPRAGE_WMn.nii.gz,1,5] -t SyN[0.25] -r Gauss[3,0] -o LIFUP020_MPRAGE_WMn -i 30x90x20 --use-Histogram-Matching --number-of-affine-iterations 10000x10000x10000x10000x10000 --MI-option 32x16000

The antsRegistration command was 
antsRegistration -d 3 --float 0 --output LIFUP020_MPRAGE_WMn -t Affine[0.1] --metric MI[templ_93x187x68.nii.gz,crop_LIFUP020_MPRAGE_T1.nii.gz,1,32,Regular,0.25] -r [rigid0GenericAffine.mat,1] --convergence [1000x500x250x100,1e-6,10] -f 8x4x2x1 -s 3x2x1x0vox -t SyN[0.25,3.0] --metric CC[templ_93x187x68.nii.gz,crop_LIFUP020_MPRAGE_T1.nii.gz,1,5] --convergence [70x90x50,1e-6,10] -f 4x2x1 -s 2x1x0vox

The files that were used to generate rigid0GenericAffine are too large to upload. You can prob. skip the -r step as it not there in ANTs. It helps if the contrasts are different which they are not here. I stripped the path names.
[templ_93x187x68.nii.gz](https://github.com/ANTsX/ANTs/files/5144480/templ_93x187x68.nii.gz)
[crop_LIFUP020_MPRAGE_WMn.nii.gz](https://github.com/ANTsX/ANTs/files/5144483/crop_LIFUP020_MPRAGE_WMn.nii.gz)

**Comment by gdevenyi** [comment] 2020-08-29 02:27
I see here your fixed image is anisotropic, the default configuration of antsRegistration is voxel-based smoothing while ANTS  is in mm space. This could be one origin of the differences. (this is why ants_generate_iterations.py outputs mm type smoothing)

**Comment by anagrammarian** [comment] 2020-09-01 00:04
Gabriel, can you help me with running ants_generate_iterations. min is the minimum resolution of the fixed file- is that the baseline resolution so 0.7x0.5x0.7mm => 0.7? max it says maximum size in mm. Not sure what size means. Is that 187*0.5 ~ 93.5mm?

**Comment by gdevenyi** [comment] 2020-09-01 00:30
That's correct

**Comment by gdevenyi** [comment] 2020-09-01 00:31
PrintHeader is useful herr

**Comment by anagrammarian** [comment] 2020-09-01 17:49
For affine, it gave
 --transform Affine[ 0.1 ] \
        --metric Mattes[ ${fixedfile},${movingfile},1,64,None ] \
        --convergence [ 450x150x50,1e-6,10 ] \
        --shrink-factors 3x2x1 \
        --smoothing-sigmas 0.600561204393x0.367767127519x0.0mm \
        --masks [ ${fixedmask},${movingmask}
Which is reasonable.

But for SyN (generic), it gave
 --convergence [ 500x500x500x500x500x500x500x500x500x500x225x75x25,1e-6,10 ] \
--shrink-factors 5x5x5x5x5x5x5x5x5x4x3x2x1 \
--smoothing-sigmas 2.75211717859x2.53910288566x2.32596354299x2.11266130337x1.89914128022x1.68532069997x1.47106851007x1.25616388301x1.04020251906x0.822352297022x0.600561204393x0.367767127519x0.0mm 

Does this make sense?

**Comment by gdevenyi** [comment] 2020-09-01 18:03
> For affine, it gave
It looks like you cut off the rest of the outputs for the affine mode. Those Translation/Rigid/Similarity/Affine levels are also important for the implementation (it's supposed to constrain the path through the affine space)

> Does this make sense?

I can't really tell since you didn't provide the exact command you ran.

**Comment by anagrammarian** [comment] 2020-09-01 18:08
Command
python ~/bin/ants_generate_iterations.py  --min 0.5 --max 87.5 --output affine

--transform Translation[ 0.1 ] \
        --metric Mattes[ ${fixedfile},${movingfile},1,32,None ] \
        --convergence [ 500x500x500x500x500x500x500,1e-6,10 ] \
        --shrink-factors 5x5x5x5x5x5x5 \
        --smoothing-sigmas 2.75211717859x2.53910288566x2.32596354299x2.11266130337x1.89914128022x1.68532069997x1.47106851007mm \
        --masks [ NOMASK,NOMASK ] \
--transform Rigid[ 0.1 ] \
        --metric Mattes[ ${fixedfile},${movingfile},1,32,None ] \
        --convergence [ 500x500x500x500x500x500x500,1e-6,10 ] \
        --shrink-factors 5x5x5x5x5x5x4 \
        --smoothing-sigmas 2.11266130337x1.89914128022x1.68532069997x1.47106851007x1.25616388301x1.04020251906x0.822352297022mm \
        --masks [ NOMASK,NOMASK ] \
--transform Similarity[ 0.1 ] \
        --metric Mattes[ ${fixedfile},${movingfile},1,32,None ] \
        --convergence [ 500x500x500x450x150,1e-6,10 ] \
        --shrink-factors 5x5x4x3x2 \
        --smoothing-sigmas 1.25616388301x1.04020251906x0.822352297022x0.600561204393x0.367767127519mm \
        --masks [ NOMASK,NOMASK ] \
--transform Similarity[ 0.1 ] \
        --metric Mattes[ ${fixedfile},${movingfile},1,32,None ] \
        --convergence [ 500x500x500x450x150,1e-6,10 ] \
        --shrink-factors 5x5x4x3x2 \
        --smoothing-sigmas 1.25616388301x1.04020251906x0.822352297022x0.600561204393x0.367767127519mm \
        --masks [ ${fixedmask},${movingmask} ] \
--transform Affine[ 0.1 ] \
        --metric Mattes[ ${fixedfile},${movingfile},1,64,None ] \
        --convergence [ 450x150x50,1e-6,10 ] \
        --shrink-factors 3x2x1 \
        --smoothing-sigmas 0.600561204393x0.367767127519x0.0mm \
        --masks [ ${fixedmask},${movingmask} ]

**Comment by anagrammarian** [comment] 2020-09-01 18:09
The other output was when I used generic instead of affine and it just had that single line with 10 or 12 levels.

**Comment by gdevenyi** [comment] 2020-09-01 18:12
Yup, looks good and as expected. Since you appear to be attempting to segment the thalamus, I suggest supplying a thalamic mask if you have one for the affine to make the affine preferentially align the tissues you're interested in. Otherwise you can drop the repeated Similarly stage which is done without/with mask.

**Comment by anagrammarian** [comment] 2020-09-01 18:15
The inputs are already largely cropped to the 2 thalami. I do have the thalamus mask for the fixed image. Do you suggest using that?

**Comment by gdevenyi** [comment] 2020-09-01 18:23
> Do you suggest using that?
I do. Possibly with some dilation.

You may also want to try the mask for the SyN stage. If you do, remember that the registration is essentially only driven by the masked area, so don't expect the rest of brain to match anymore. If you goal is to match thalami to thalami, that shouldn't matter.

**Comment by gdevenyi** [comment] 2020-09-01 18:24
Since you seem to be attempting to segment something via registration, you may be interested in our MAGeT Brain pipeline which does the same thing (and uses these ideas) https://github.com/cobralab/antsRegistration-MAGeT, and we have a number of atlases; https://github.com/cobralab/atlases

**Comment by ntustison** [comment] 2020-09-01 18:27
You might want to also look at our [deep learning capabilities](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/desikan_killiany_tourville_labeling.py#L25-L128) to register anatomical masks directly.  Specifically, this function will provide an entire anatomic parcellation you could use for both fixed and moving images, including the thalamus.

**Comment by anagrammarian** [comment] 2020-09-01 18:27
I have looked at MaGET. We use white matter nulled MPRAGE and have manual segmentations based on that from 7T which we believe to be far better than those using conventional MPRAGE as the contrast has been optimized to bring out intrathalamic contrast. https://pubmed.ncbi.nlm.nih.gov/30894331/

**Comment by anagrammarian** [comment] 2020-09-01 18:31
Nick, we are segmenting thalamic nuclei not the whole thalamus (which is pretty easy with WM nulled MPRAGE actually as the contrast is fantastic). We already have a deep learning based segmentation which we just published which is good but still not robust when there are lesions or veins or dropouts from metal mainly due to lack of training. https://www.sciencedirect.com/science/article/pii/S0730725X20303118?casa_token=zW1QDTr5IrMAAAAA:5kNLBaQXlnn0kHSSo-ymXxWx6pX2eOlo2KoocDsVx15tBTNmSmETAIgK30NM_fFYcIn-6fY43qU

**Comment by ntustison** [comment] 2020-09-01 18:33
Okay, just a thought.  It's something that's actually publicly available and can be used as part of any registration protocol.

**Comment by gdevenyi** [comment] 2020-09-01 18:35
>  We use white matter nulled MPRAGE and have manual segmentations based on that from 7T
Cool, MAGeT is a method, not just an atlas set, so you could provide all your own input atlases :)

**Comment by anagrammarian** [comment] 2020-09-01 18:37
Yes incorporating MAGeT to broaden our limited manual prior atlases is on my plate but too many projects, too little time ;) Ideally, we want to eliminate registration which is suboptimal in large ventricles or poor contrast or motion. Deep learning segmentation seems to be pretty good but needs more training. So eventually I want to use a MAGET like framework to generate more priors yes. If you have a student who is interested, let me know ;)

**Comment by anagrammarian** [comment] 2020-09-01 20:48
Gabriel, no matter what I try, I still cannot get the ventricles aligned right like shown in the arrow.

**Comment by stnava** [comment] 2020-09-01 20:49
increase the gradient step size.

brian

**Comment by anagrammarian** [comment] 2020-09-01 20:53
Ha, exactly what I am trying now. How high can I go?

**Comment by stnava** [comment] 2020-09-01 20:59
you might also change --convergence [70x90x50,1e-6,10]  to --convergence
[200x200x90x50,1e-10,10]

i think we used up to 0.5 in the klein evaluation but this may cause some
topology problems - just small local issues of "confusion" about the
fwd/inverse mapping

brian

**Comment by anagrammarian** [comment] 2020-09-01 21:01
So 4 levels and increase step size? Will try a bunch of steps all the way to 0.5

**Comment by anagrammarian** [comment] 2020-09-01 21:22
0.4 was already better. Weird because I did play with this but did not go beyond 0.35. I am running a few cases to make sure they look decent.

**Comment by anagrammarian** [comment] 2020-09-01 23:49
I am getting pretty good results with 0.4. The interesting thing is old ANTS was using 0.25 to achieve the same sort of perfomance. I bumped up the iterations like you suggested. Regn time is now 17 min or so up from 11 min. I think that's fine. One issue I need to fully investigate is I am getting pretty different (worse) performance with using ANTS from the latest build than I was getting from ANTS 2.1. I have the same scripts so everything is identical. I will look at it one more time tomorrow. For now, I am happy with antsRegistration. Thanks everyone.

**Comment by anagrammarian** [comment] 2020-09-02 18:08
OK I reanalyzed a bunch of old data (which had been segmented with ANTS using ANTS 2.1) with the new antsRegistration on the latest version. The volumes match quite nicely and registration looks much better. The bad news is repeating with ANTS the same old command doesn't produce good results. I am not too worried as at least antsRegistration is behaving OK. It is still a bit longer but not a big deal. Thanks again to everyone Gabriel and Nick particularly for helping track this down.

**Comment by stnava** [comment] 2020-09-02 18:14
would be nice if you shared more details

* what parameters match best to the old ANTS *

culprit probably some change in the smoothing functions in ITK.

brian

**Comment by anagrammarian** [comment] 2020-09-02 18:16
I will definitely do that once I have tested it thoroughly on data from various scanners so I am not speaking too soon. In a day or so.

**Comment by anagrammarian** [comment] 2020-09-10 04:51
OK I ran it on a set of 20 cases where I have manual segmentations and compared old ANTS vs new antsRegistration.  The old ANTS command was 
ANTS 3 -m CC[/home/manojsar/thomas_new/templ_93x187x68.nii.gz,temp/crop_wmn.nii.gz,1,5] -t SyN[0.25] -r Gauss[3,0] -o LIFUP020_MPRAGE_WMn -i 30x90x20 --use-Histogram-Matching --number-of-affine-iterations 10000x10000x10000x10000x10000 --MI-option 32x16000

antsRegistration -v -d 3 --float 0 --output temp/wmn --use-histogram-matching 1 -t Rigid[0.1] --metric Mattes[/home/manojsar/thomas_new/templ_93x187x68.nii.gz,temp/crop_wmn.nii.gz,1,32,None] --convergence [500x500x500x500x500,1e-6,10] -f 5x5x5x5x4 -s 1.685x1.4771x1.256x1.0402x0.82235mm -r [rigid0GenericAffine.mat,1] -t Affine[0.1] --metric Mattes[/home/manojsar/thomas_new/templ_93x187x68.nii.gz,temp/crop_wmn.nii.gz,1,64, None] --convergence [450x150x50,1e-7,10] -f 3x2x1 -s 0.60056x0.3677x0mm -t SyN[0.4,3.0] --metric CC[/home/manojsar/thomas_new/templ_93x187x68.nii.gz,temp/crop_wmn.nii.gz,1,5] --convergence [200x200x90x50,1e-10,10] -f 4x3x2x1 -s 0.82x0.6x0.3677x0.0mm

It seems like both the SyN argument 0.4 grad step and the shrink factor smoothing factor changes were needed to get it comparable. It is still not perfect but the Dices were within 0.01 and the Bland Altman plots almost identical. Old ANTs was also faster (on my Dell 4 core, it was 12 min. vs. 20 min. on the average). I still ran jointfusion (PICSL) instead ants joint fusion for both.

I can prob. shave a few min off by playing carefully with the levels etc but I don't see the point at this time. I am calling it quits and closing this chapter.

One disappointing thing is the ANTS in the latest release behaves much worse than the 2.1 ANTs. Again something I am not going to bother looking into as antsRegistration is working comparably almost.

**Comment by stnava** [comment] 2020-09-10 09:21
thanks for getting back to us.

@cookpa and @ntustison graciously pushed a fix to the old ANTS just
recently which may resolve the performance issue.   there was a rather
major bug in the upsampling of the deformation field between levels.

brian

**Closed** 2020-11-02 17:12 UTC
