### ISSUE TITLE
can't read initial transform ANTs0GenericAffine.mat

### ISSUE THREAD

**Issue by carolin31** [ANTsX/ANTs#614] opened 2018-07-25 21:47 UTC
Hi,

I am trying to run antsApplyTransforms to apply the transformation parameters from a structural-to-template warping to functional data (bucket data set from afni, which contains several sub-bricks with each sub-brick giving beta weights or t-values for a specific regressor of interest). structural and functional data have been of course previously coregisterd to each other.
I used the following code:
antsApplyTransforms -d 4 -v 1 -r Zach_Template.nii -i stats.s201_REML.nii -o stats_warped_ -t ANTs1Warp.nii.gz -t ANTs0GenericAffine.mat

I get the following message:

Using double precision for computations.
Input scalar image: stats.s201_REML.nii
Reference image: Zach_Template.nii
Can't read initial transform ANTs0GenericAffine.mat

I found that somebody posted a similar problem on source forge:https://sourceforge.net/p/advants/discussion/840261/thread/c0485b2c/?limit=25

I still don t understand what causes the problem and how I can fix it?

Thank you in advance 
Carolin

**Comment by ntustison** [comment] 2018-07-25 22:14
Hi @carolin31 , Can you post the data so I can check it on my machine?

**Comment by carolin31** [comment] 2018-07-25 23:47
Hi Nick,

thank you very much for the quick response. The data is on Zion. Here is
the link:

/tmp/yassamri/R21/caro/201/ANTs


Let me know, if you should not be able to access them.

Thanks again!

Caro

**Comment by ntustison** [comment] 2018-07-26 14:30
I don't know what the problem is.  You have a couple things incorrect on your command line but they don't have anything to do with the error your getting.  However, fix them with the command below and tell me what you get.

```
$ antsApplyTransforms -d 3 -v 1 -r Zach_Template.nii -i stats.s201_REML.nii -o stats_warped.nii.gz -t ANTs1Warp.nii.gz -t ANTs0GenericAffine.mat
```

**Comment by ntustison** [comment] 2018-07-27 03:37
Hi @carolin31 ,

ITK nifti I/O reads the stats.s201_REML.nii image as a 3-D image with each voxel having 30+ components.  Note how this is different from a 4-D image where the fourth dimension is used to store the 30+ components.  The latter could be handled via the time-series option in ``antsApplyTransforms``.  Can you extract each of these components to separate scalar 3-D volumes?  

Nick

**Comment by carolin31** [comment] 2018-07-31 18:11
Hi Nick, 
so are you saying that I can not use antsApplyTransforms on this kind of dataset? And that I have to find a way to first transform the stats file into individual images?

A related question that I would have then, what is the difference between the -d4 option and using -e3? I tried to run the -d 4 option on a time series and it didn't t work either. I get the same error message: Can 't read initial transform ANTs0GenericAffine.mat. But the -e3 option worked on the time series  (but not on my stats dataset).
Could you give an example for what kind of dataset the -d4 option can be used?

Thanks a lot!
Caro

**Comment by stnava** [comment] 2018-07-31 18:33
in itk, this is ( i think ) a vector image.  in antsr, we call it multichannel.   i recall in v4 that we developed interpolators for this type so it would probably be a matter of typedefs and UI work to add.   i think it's already in antsr - certainly via `splitMultiChannel` and `mergeMultiChannel` functions if not via direct call to some transformation function.   @cookpa or @jeffduda   may know something more.

brian

**Comment by ntustison** [comment] 2018-07-31 18:52
Okay, I'll put it on my to-do list.  Shouldn't be too hard.

**Comment by carolin31** [comment] 2018-07-31 19:01
This would be great. 
I believe that afni is an often used software in fMRI analysis and having to transform the functional images into a common template space is a standard processing step when one wants to do group analysis. We like using ANTs for the normalization because it does a better job than afni, and I just learned that we also had to generate a script, which separates the afni stats data set into individual images and puts it later together again. Unfortunately this script is outdated and does not include the newer antsApplyTransform function.

**Comment by carolin31** [comment] 2018-07-31 22:55
Will the older Ants function 'WarpImageMultiTransform' lead to a worse result than when I use antsApplyTransforms?

**Comment by ntustison** [comment] 2018-07-31 23:36
@stnava Another option would be to open up ``dimension = 5`` in ``ExtractSliceFromImage`` and then create an inverse operation somewhere.

**Comment by ntustison** [comment] 2018-08-01 02:43
Sounds good.

**Comment by cookpa** [comment] 2018-08-01 16:29
Is it necessary to handle the 5D convention explicitly? I think the ITK NIFTI reader can read it into an ITK vector image.

In NIFTI the 4th dimension is reserved for time. So a multi-component image that does not represent a time series is (NIFTI_INTENT_VECTOR) is 5D with dimensions X,Y,Z,1,N for N components. By NIFTI_INTENT_VECTOR they mean an array of scalar values, not necessarily a vector with any physical interpretation like a warp field.

Color and complex images have a non-scalar pixel type, but not a 5th dimension. So an RGB image from DTI is 3D but has datatype code DT_RGB = 128 in the NIFTI header. This is stored as an array of 24-bit pixels, rather than as three volumes of R, G, B. But I think ITK handles this - at least it reads into SNAP no problem.

**Comment by cookpa** [comment] 2018-12-03 19:51
I believe this issue was fixed by https://github.com/ANTsX/ANTs/commit/3735311732d3b8f8bcb8c95fe386aac3b657c7e2

**Comment by ntustison** [comment] 2021-05-13 00:05
https://github.com/ANTsX/ANTs/pull/1191

**Closed** 2023-05-02 13:06 UTC
